In [1]:
from splinter import Browser
from bs4 import BeautifulSoup
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
from selenium import webdriver

In [7]:
df_usa = pd.read_csv('us_wines.csv')

In [8]:
df2 = df_usa
df2 = df2['location'].str.split(',', expand=True)

In [9]:
df2 = df2.rename(columns={0 : "region", 1 : "country"})
df2

                  region         country
0            Napa Valley   United States
1            Napa Valley   United States
2    Stags Leap District   United States
3               Oakville   United States
4         Knights Valley   United States
..                   ...             ...
545   Santa Maria Valley   United States
546       Ballard Canyon   United States
547          Napa Valley   United States
548          Napa Valley   United States
549           St. Helena   United States

[550 rows x 2 columns]

In [10]:
df_usa = df_usa.join(df2)
df_usa

,Unnamed: 0,brand,vintage,rating,price,num_ratings,location,region,country
0,0,Adeptos,Reserve Cabernet Sauvignon 2018,4.2,32.99,84,"Napa Valley, United States",Napa Valley,United States
1,1,Vinium,Reserve Cabernet Sauvignon 2018,4.3,34.99,86,"Napa Valley, United States",Napa Valley,United States
2,2,Dolum Estates,Cask 28 Cabernet Sauvignon 2019,4.4,34.99,80,"Stags Leap District, United States",Stags Leap District,United States
3,3,Sling & Spear,Cabernet Sauvignon 2018,4.3,44.99,110,"Oakville, United States",Oakville,United States
4,4,St. Clement,Johanna Cabernet Sauvignon 2019,4.1,24.99,163,"Knights Valley, United States",Knights Valley,United States
...,...,...,...,...,...,...,...,...,...
545,545,Foxen,Block 8 Pinot Noir (Bien Nacido Vineyard) 2017,4.4,59.90,70,"Santa Maria Valley, United States",Santa Maria Valley,United States
546,546,Jonata,La Sangre de Jonata 2009,4.4,160.60,70,"Ballard Canyon, United States",Ballard Canyon,United States
547,547,Arietta,Quartet 2019,4.4,73.99,69,"Napa Valley, United States",Napa Valley,United States
548,548,Alpha Omega,Proprietary Red 2019,4.4,159.99,68,"Napa Valley, United States",Napa Valley,United States
549,549,Salvestrin,Cabernet Sauvignon Dr. Crane Vineyard Three D ...,4.4,169.99,67,"St. Helena, United States",St. Helena,United States

In [11]:
df_usa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   550 non-null    int64
 1   brand        550 non-null    object
 2   vintage      550 non-null    object
 3   rating       550 non-null    float64
 4   price        550 non-null    float64
 5   num_ratings  550 non-null    int64
 6   location     550 non-null    object
 7   region       550 non-null    object
 8   country      550 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 38.8+ KB

In [12]:
df_usa = df_usa.drop("location", axis=1)
df_usa

,Unnamed: 0,brand,vintage,rating,price,num_ratings,region,country
0,0,Adeptos,Reserve Cabernet Sauvignon 2018,4.2,32.99,84,Napa Valley,United States
1,1,Vinium,Reserve Cabernet Sauvignon 2018,4.3,34.99,86,Napa Valley,United States
2,2,Dolum Estates,Cask 28 Cabernet Sauvignon 2019,4.4,34.99,80,Stags Leap District,United States
3,3,Sling & Spear,Cabernet Sauvignon 2018,4.3,44.99,110,Oakville,United States
4,4,St. Clement,Johanna Cabernet Sauvignon 2019,4.1,24.99,163,Knights Valley,United States
...,...,...,...,...,...,...,...,...
545,545,Foxen,Block 8 Pinot Noir (Bien Nacido Vineyard) 2017,4.4,59.90,70,Santa Maria Valley,United States
546,546,Jonata,La Sangre de Jonata 2009,4.4,160.60,70,Ballard Canyon,United States
547,547,Arietta,Quartet 2019,4.4,73.99,69,Napa Valley,United States
548,548,Alpha Omega,Proprietary Red 2019,4.4,159.99,68,Napa Valley,United States
549,549,Salvestrin,Cabernet Sauvignon Dr. Crane Vineyard Three D ...,4.4,169.99,67,St. Helena,United States

In [13]:
df_usa = df_usa.drop("Unnamed: 0", axis=1)
df_usa

,brand,vintage,rating,price,num_ratings,region,country
0,Adeptos,Reserve Cabernet Sauvignon 2018,4.2,32.99,84,Napa Valley,United States
1,Vinium,Reserve Cabernet Sauvignon 2018,4.3,34.99,86,Napa Valley,United States
2,Dolum Estates,Cask 28 Cabernet Sauvignon 2019,4.4,34.99,80,Stags Leap District,United States
3,Sling & Spear,Cabernet Sauvignon 2018,4.3,44.99,110,Oakville,United States
4,St. Clement,Johanna Cabernet Sauvignon 2019,4.1,24.99,163,Knights Valley,United States
...,...,...,...,...,...,...,...
545,Foxen,Block 8 Pinot Noir (Bien Nacido Vineyard) 2017,4.4,59.90,70,Santa Maria Valley,United States
546,Jonata,La Sangre de Jonata 2009,4.4,160.60,70,Ballard Canyon,United States
547,Arietta,Quartet 2019,4.4,73.99,69,Napa Valley,United States
548,Alpha Omega,Proprietary Red 2019,4.4,159.99,68,Napa Valley,United States
549,Salvestrin,Cabernet Sauvignon Dr. Crane Vineyard Three D ...,4.4,169.99,67,St. Helena,United States